CREATE TABLE IF NOT EXISTS vehicle(
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  MODEL VARCHAR(255) NOT NULL,
  CONST_DATE INTEGER NOT NULL,
  DESCRIPTION VARCHAR(255),
  SEATING INTEGER,
  LICENSE VARCHAR(255),
  PLATE VARCHAR(255),
  TYPE VARCHAR(255) NOT NULL,
  POWER DOUBLE,
  PRICE DOUBLE NOT NULL,
  CREATE_DATE TIMESTAMP NOT NULL,
  PICTURE VARCHAR(255),
  UPDATE_DATE TIMESTAMP,
  ISACTIVE BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS booking(
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(255) NOT NULL,
  PAYMENT_INFO VARCHAR(255) NOT NULL,
  FROM_DATETIME TIMESTAMP NOT NULL,
  TO_DATETIME TIMESTAMP NOT NULL,
  TOTAL_PRICE DOUBLE,
  STATUS VARCHAR(255) NOT NULL,
  DATE_OF_ISSUE TIMESTAMP NOT NULL,
  BILLING_DATE TIMESTAMP
);

CREATE TABLE IF NOT EXISTS booking_vehicle(
  BOOKING_ID INTEGER,
  FOREIGN KEY (BOOKING_ID) REFERENCES booking(ID),
  VEHICLE_ID INTEGER,
  FOREIGN KEY (VEHICLE_ID) REFERENCES vehicle(ID),
  BOOKING_PRICE DOUBLE,
  PRIMARY KEY (BOOKING_ID, VEHICLE_ID),
  LICENSE_NUMBER VARCHAR(255),
  LICENSE_DATE DATE,
  MODEL VARCHAR(255)
);